<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7RZOkGX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7RZOkGX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7RZOkGX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7RZOkGX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7RZOkGX\App_KernelDevDebugContainer([
    'container.build_hash' => '7RZOkGX',
    'container.build_id' => 'ddf12ee4',
    'container.build_time' => 1649772585,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7RZOkGX');
