<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPQwEMF4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPQwEMF4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPQwEMF4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPQwEMF4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPQwEMF4\App_KernelDevDebugContainer([
    'container.build_hash' => 'PQwEMF4',
    'container.build_id' => '228906ad',
    'container.build_time' => 1651671895,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPQwEMF4');
