<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXUXx85v\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXUXx85v/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXUXx85v.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXUXx85v\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXUXx85v\App_KernelDevDebugContainer([
    'container.build_hash' => 'XUXx85v',
    'container.build_id' => '029a2e24',
    'container.build_time' => 1652173390,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXUXx85v');
